BORDER = (0, 0, 0)
GREY = (170, 170, 170)
WHITE = (255, 255, 255)
BACKGROUND = (169, 216, 255)
CHECKBOX = (30, 79, 131)
BRIGHT_GREEN_RGB = (113, 255, 66)

CORRECTION_VALUE = 0

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 900
WINDOW_TITLE = "HyperGUI"
WINDOW_SIZE = str(WINDOW_WIDTH) + "x" + str(WINDOW_HEIGHT)

NONE = "NONE"
RGB = "RGB"
STO2 = "STO2"
NIR = "NIR"
THI = "THI"
TWI = "TWI"

WL = "WL"
IDX = "IDX"

ABSORPTION_SPEC = "ABSORPTION_SPEC"
ANALYSIS_AND_FORM = "ANALYSIS_AND_FORM"
DIAGRAM = "DIAGRAM"
HISTOGRAM = "HISTOGRAM"
NEW_COLOUR = "NEW_COLOUR"
NEW_COLOUR_DATA = "NEW_COLOUR_DATA"
ORIGINAL_COLOUR = "ORIGINAL_COLOUR"
ORIGINAL_COLOUR_DATA = "ORIGINAL_COLOUR_DAT"
RECREATED_COLOUR = "RECREATED_COLOUR"
RECREATED_COLOUR_DATA = "RECREATED_COLOUR_DATA"
SAVE = "SAVE"
SOURCE_AND_OUTPUT = "SOURCE_AND_OUTPUT"
INFO = "INFO"
CSV = "CSV"
PARAMETER = "PARAMETER"

# SAVES
WHOLE_IMAGE_SAVE = "WHOLE_IMAGE_SAVE"
MASKED_IMAGE_SAVE = "MASKED_IMAGE_SAVE"
STO2_DATA = "STO2_DATA"
NIR_DATA = "NIR_DATA"
TWI_DATA = "TWI_DATA"
THI_DATA = "THI_DATA"
OG_IMAGE = "OG_IMAGE"
OG_RGB_DATA = "OG_RGB_DATA"
OG_STO2_DATA = "OG_STO2_DATA"
OG_NIR_DATA = "OG_NIR_DATA"
OG_TWI_DATA = "OG_TWI_DATA"
OG_THI_DATA = "OG_THI_DATA"
REC_IMAGE = "REC_IMAGE"
REC_IMAGE_WO_SCALE = "REC_IMAGE_WO_SCALE"
WL_DATA = "WL_DATA"
IDX_DATA = "IDX_DATA"
NEW_IMAGE = "NEW_IMAGE"
NEW_IMAGE_WO_SCALE = "NEW_IMAGE_WO_SCALE"
HISTOGRAM_IMAGE = "HISTOGRAM_IMAGE"
HISTOGRAM_IMAGE_WO_SCALE = "HISTOGRAM_IMAGE_WO_SCALE"
HISTOGRAM_EXCEL = "HISTOGRAM_EXCEL"
ABSORPTION_SPEC_IMAGE = "ABSORPTION_SPEC_IMAGE"
ABSORPTION_SPEC_IMAGE_WO_SCALE = "ABSORPTION_SPEC_IMAGE_WO_SCALE"
ABSORPTION_SPEC_EXCEL = "ABSORPTION_SPEC_EXCEL"

# POINTS
PT1 = "PT1"
PT2 = "PT2"
PT3 = "PT3"
PT4 = "PT4"
PT5 = "PT5"
PT6 = "PT6"
PT7 = "PT7"
PT8 = "PT8"
PT9 = "PT9"
PT10 = "PT10"

# FILES
RGB_FILE = "_RGB-Image.png"
STO2_FILE = "_Oxygenation.png"
NIR_FILE = "_NIR-Perfusion.png"
THI_FILE = "_THI.png"
TWI_FILE = "_TWI.png"
