PASTEL_BLUE_RGB = (206, 225, 255)
PASTEL_ORANGE_RGB = (255, 215, 160)
PASTEL_PINK_RGB = (221, 206, 255)

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 900
WINDOW_TITLE = "GutGUI"
WINDOW_SIZE = str(WINDOW_WIDTH) + "x" + str(WINDOW_HEIGHT)

NONE = "NONE"
STO2 = "STO2"
NIR = "NIR"
THI = "THI"
TWI = "TWI"

WL = "WL"
IDX = "IDX"

ABSORPTION_SPEC = "ABSORPTION_SPEC"
ANALYSIS_AND_FORM = "ANALYSIS_AND_FORM"
DIAGRAM = "DIAGRAM"
HISTOGRAM = "HISTOGRAM"
NEW_COLOUR = "NEW_COLOUR"
ORIGINAL_COLOUR = "ORIGINAL_COLOUR"
RECREATED_COLOUR = "RECREATED_COLOUR"
SAVE = "SAVE"
SOURCE_AND_OUTPUT = "SOURCE_AND_OUTPUT"

# SAVES
WHOLE_IMAGE_SAVE = "WHOLE_IMAGE_SAVE"
MASKED_IMAGE_SAVE = "MASKED_IMAGE_SAVE"
STO2_DATA = "STO2_DATA"
NIR_DATA = "NIR_DATA"
TWI_DATA = "TWI_DATA"
THI_DATA = "THI_DATA"
REC_IMAGE = "REC_IMAGE"
REC_IMAGE_WO_SCALE = "REC_IMAGE_WO_SCALE"
WL_DATA = "WL_DATA"
IDX_DATA = "IDX_DATA"
NEW_IMAGE = "NEW_IMAGE"
NEW_IMAGE_WO_SCALE = "NEW_IMAGE_WO_SCALE"
HISTOGRAM_IMAGE = "HISTOGRAM_IMAGE"
HISTOGRAM_IMAGE_WO_SCALE = "HISTOGRAM_IMAGE_WO_SCALE"
HISTOGRAM_EXCEL = "HISTOGRAM_EXCEL"
ABSORPTION_SPEC_IMAGE = "ABSORPTION_SPEC_IMAGE"
ABSORPTION_SPEC_IMAGE_WO_SCALE = "ABSORPTION_SPEC_IMAGE_WO_SCALE"
ABSORPTION_SPEC_EXCEL = "ABSORPTION_SPEC_EXCEL"
