PASTEL_BLUE_RGB = (206, 225, 255)
PASTEL_ORANGE_RGB = (255, 215, 160)
PASTEL_PINK_RGB = (221, 206, 255)

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 900
WINDOW_TITLE = "GutGUI"
WINDOW_SIZE = str(WINDOW_WIDTH) + "x" + str(WINDOW_HEIGHT)

NONE = "NONE"
STO2 = "STO2"
NIR = "NIR"
THI = "THI"
TWI = "TWI"

WL = "WL"
IDX = "IDX"

ABSORPTION_SPEC = "ABSORPTION_SPEC"
ANALYSIS_AND_FORM = "ANALYSIS_AND_FORM"
DIAGRAM = "DIAGRAM"
HISTOGRAM = "HISTOGRAM"
NEW_COLOUR = "NEW_COLOUR"
ORIGINAL_COLOUR = "ORIGINAL_COLOUR"
RECREATED_COLOUR = "RECREATED_COLOUR"
SAVE = "SAVE"
SOURCE_AND_OUTPUT = "SOURCE_AND_OUTPUT"